"""
Centralized validation errors, warnings, and informational messages.

Defines the core validation data types (ValidationLevel, ValidationType,
ValidationResult, ValidationReport) and factory functions that produce
fully constructed ValidationResult instances.  Both CpmValidator
(validation.py) and AnalysisMixin (model/analysis.py) import from here
so that wording and severity are consistent.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional

from prov.identifier import QualifiedName


# ═══════════════════════════════════════════════════════════════════════════
# Core data types
# ═══════════════════════════════════════════════════════════════════════════

class ValidationLevel(Enum):
    """Validation severity levels"""
    ERROR = "ERROR"
    WARNING = "WARNING"
    INFO = "INFO"


class ValidationType(Enum):
    """Types of validation checks"""
    STRUCTURAL = "STRUCTURAL"
    SEMANTIC = "SEMANTIC"
    TEMPLATE_COMPLIANCE = "TEMPLATE_COMPLIANCE"
    CROSS_PART = "CROSS_PART"
    TRAVERSAL = "TRAVERSAL"


@dataclass
class ValidationResult:
    """Individual validation result"""
    level: ValidationLevel
    validation_type: ValidationType
    message: str
    node_id: Optional[QualifiedName] = None
    edge_id: Optional[QualifiedName] = None
    bundle_id: Optional[QualifiedName] = None
    details: Optional[Dict[str, Any]] = None


@dataclass
class ValidationReport:
    """Complete validation report"""
    results: List[ValidationResult]
    is_valid: bool
    error_count: int
    warning_count: int
    info_count: int

    def get_errors(self) -> List[ValidationResult]:
        return [r for r in self.results if r.level == ValidationLevel.ERROR]

    def get_warnings(self) -> List[ValidationResult]:
        return [r for r in self.results if r.level == ValidationLevel.WARNING]

    def get_by_type(self, validation_type: ValidationType) -> List[ValidationResult]:
        return [r for r in self.results if r.validation_type == validation_type]


# ═══════════════════════════════════════════════════════════════════════════
# Structural – Main Activity
# ═══════════════════════════════════════════════════════════════════════════

def no_main_activity() -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message="Document contains no Main Activity",
    )


def multiple_main_activities(ids: str) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message=f"Document contains multiple Main Activities: {ids}",
    )


# ═══════════════════════════════════════════════════════════════════════════
# Structural – Connectors
# ═══════════════════════════════════════════════════════════════════════════

def connector_missing_bundle_id(connector_id) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message=f"Connector {connector_id} missing required cpm:referencedBundleId",
        node_id=connector_id,
    )


def connector_missing_hash(connector_id) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.WARNING,
        validation_type=ValidationType.STRUCTURAL,
        message=f"Connector {connector_id} missing cpm:referencedBundleHashValue",
        node_id=connector_id,
    )


def backward_connector_not_used(connector_id) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message=f"Backward Connector {connector_id} not used by Main Activity",
        node_id=connector_id,
    )


def forward_connector_not_generated(connector_id) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message=f"Forward Connector {connector_id} not generated by Main Activity",
        node_id=connector_id,
    )


# ═══════════════════════════════════════════════════════════════════════════
# Connectivity
# ═══════════════════════════════════════════════════════════════════════════

def graph_not_connected(reachable: int, total: int) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.TRAVERSAL,
        message=f"Graph not fully connected: {reachable}/{total} nodes reachable",
        details={"reachable_nodes": reachable, "total_nodes": total},
    )


def orphaned_node(node_id) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.WARNING,
        validation_type=ValidationType.STRUCTURAL,
        message=f"Node {node_id} is not reachable from the Main Activity",
        node_id=node_id,
    )


# ═══════════════════════════════════════════════════════════════════════════
# PROV constraints (defensive)
# ═══════════════════════════════════════════════════════════════════════════

def invalid_usage_relation(cause_kind, effect_kind, edge_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.SEMANTIC,
        message=(
            f"Invalid Usage relation: expected Entity -> Activity, "
            f"got {cause_kind} -> {effect_kind}"
        ),
        edge_id=edge_id,
    )


def invalid_generation_relation(cause_kind, effect_kind, edge_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.SEMANTIC,
        message=(
            f"Invalid Generation relation: expected Activity -> Entity, "
            f"got {cause_kind} -> {effect_kind}"
        ),
        edge_id=edge_id,
    )


def invalid_association_relation(cause_kind, effect_kind, edge_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.SEMANTIC,
        message=(
            f"Invalid Association relation: expected Activity -> Agent, "
            f"got {cause_kind} -> {effect_kind}"
        ),
        edge_id=edge_id,
    )


# ═══════════════════════════════════════════════════════════════════════════
# Node / Edge integrity
# ═══════════════════════════════════════════════════════════════════════════

def node_missing_identifier(node_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message="Node missing identifier",
        node_id=node_id,
    )


def node_no_elements(node_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message="Node has no elements",
        node_id=node_id,
    )


def isolated_node(node_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.WARNING,
        validation_type=ValidationType.STRUCTURAL,
        message="Isolated node detected",
        node_id=node_id,
    )


def edge_missing_cause(edge_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message="Edge missing cause node",
        edge_id=edge_id,
    )


def edge_missing_effect(edge_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message="Edge missing effect node",
        edge_id=edge_id,
    )


def edge_no_relations(edge_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message="Edge has no relations",
        edge_id=edge_id,
    )


def self_loop_edge(edge_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.WARNING,
        validation_type=ValidationType.STRUCTURAL,
        message="Self-loop edge detected",
        edge_id=edge_id,
    )


# ═══════════════════════════════════════════════════════════════════════════
# Bundle structure
# ═══════════════════════════════════════════════════════════════════════════

def empty_bundle(bundle_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.WARNING,
        validation_type=ValidationType.STRUCTURAL,
        message="Empty bundle detected",
        bundle_id=bundle_id,
    )


def no_bundles() -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.INFO,
        validation_type=ValidationType.STRUCTURAL,
        message="No bundles found in document",
    )


# ═══════════════════════════════════════════════════════════════════════════
# Attribute consistency
# ═══════════════════════════════════════════════════════════════════════════

def inconsistent_node_types(types, node_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.WARNING,
        validation_type=ValidationType.SEMANTIC,
        message=f"Node has elements with inconsistent types: {types}",
        node_id=node_id,
        details={"types": list(types)},
    )


# ═══════════════════════════════════════════════════════════════════════════
# Cross-part / traversal
# ═══════════════════════════════════════════════════════════════════════════

def cross_part_not_marked(edge_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.CROSS_PART,
        message="Cross-part edge not properly marked",
        edge_id=edge_id,
    )


def high_traversal_cost(cost: float, edge_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.WARNING,
        validation_type=ValidationType.TRAVERSAL,
        message=f"High traversal cost: {cost}",
        edge_id=edge_id,
        details={"traversal_cost": cost},
    )


# ═══════════════════════════════════════════════════════════════════════════
# Template compliance
# ═══════════════════════════════════════════════════════════════════════════

def template_missing_main_activity(template_main_activity_id=None) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.TEMPLATE_COMPLIANCE,
        message="Missing required main activity",
        details={"template_main_activity": template_main_activity_id},
    )


def template_missing_backward_connectors(expected: int) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.WARNING,
        validation_type=ValidationType.TEMPLATE_COMPLIANCE,
        message="Template specifies backward connectors but none found in graph",
        details={"expected_backward_connectors": expected},
    )


def template_missing_forward_connectors(expected: int) -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.WARNING,
        validation_type=ValidationType.TEMPLATE_COMPLIANCE,
        message="Template specifies forward connectors but none found in graph",
        details={"expected_forward_connectors": expected},
    )


# ═══════════════════════════════════════════════════════════════════════════
# TI/DS completeness
# ═══════════════════════════════════════════════════════════════════════════

def no_ti_nodes() -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message="No traversal information nodes found",
    )


def no_ds_nodes() -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.INFO,
        validation_type=ValidationType.STRUCTURAL,
        message="No domain-specific nodes found - consider adding domain context",
    )


# ═══════════════════════════════════════════════════════════════════════════
# Generic
# ═══════════════════════════════════════════════════════════════════════════

def validation_rule_failed(error, rule_name: str = "") -> ValidationResult:
    return ValidationResult(
        level=ValidationLevel.ERROR,
        validation_type=ValidationType.STRUCTURAL,
        message=f"Validation rule failed: {error}",
        details={"exception": str(error), "rule": rule_name},
    )
